- hosts: deepschool_host
  tasks:
    - name: create workdir
      file:
        path: '{{ playbook_dest }}'
        state: directory
        owner: '{{ ansible_user }}'
      tags: [ 'prepare' ]

    - name: create run script
      template:
        dest: '{{ playbook_dest }}/run.sh'
        src: 'templates/run.sh'
        mode: 0755
      tags: ['prepare']

    - name: transfer files
      copy:
        src: "{{ item }}"
        dest: "{{ playbook_dest }}/"
        owner: "{{ ansible_user }}"
        mode: "0644"
      loop:
        - "config"  # Копирует содержимое директории
        - "src"
        - "config"
        - "app.py"
        - "Dockerfile"
        - "requirements.txt"
        - "Makefile"
      tags: [ 'prepare' ]

    - name: run
      command: "./run.sh"
      args:
        chdir: "{{ playbook_dest }}"
      ignore_errors: true
      tags: [ 'run' ]
